# This is a configuration file for the bacon tool
#
# Complete help on configuration: https://dystroy.org/bacon/config/

default_job = "check"
env.CARGO_TERM_COLOR = "always"

[jobs.check]
command = ["cargo", "check"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--all-targets"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy"]
need_stdout = false

[jobs.clippy-all]
command = ["cargo", "clippy", "--all-targets"]
need_stdout = false

[jobs.test]
command = ["cargo", "test"]
need_stdout = true

[jobs.nextest]
command = [
  "cargo",
  "nextest",
  "run",
  "--hide-progress-bar",
  "--failure-output",
  "final",
]
need_stdout = true
analyzer = "nextest"

[jobs.doc]
command = ["cargo", "doc", "--no-deps"]
need_stdout = false

[jobs.doc-open]
command = ["cargo", "doc", "--no-deps", "--open"]
need_stdout = false
on_success = "back"                               # so that we don't open the browser at each change

[jobs.ex]
command = ["cargo", "run", "--example"]
need_stdout = true
allow_warnings = true

[jobs.rdme]
command = ["cargo", "rdme", "--force"]
need_stdout = true
allow_warnings = true
background = true
default_watch = false
watch = ["./src/lib.rs"]

[keybindings]
c = "job:clippy"
r = "job:rdme"
