name: Test

on:
    push:
        branches: ["main"]
    pull_request:

# Cancel in-progress workflows for a PR if it is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install stable toolchain
              run: |
                rustup toolchain install stable --profile minimal
                rustup component add clippy

            - name: Install libpango dependency
              run: sudo apt-get install libpango1.0-dev

            - name: Cache dependencies
              uses: Swatinem/rust-cache@v2

            - name: Check
              run: cargo check

            - name: Build
              run: cargo build --verbose

            - name: Format
              run: cargo fmt --check

            - name: Lint
              run: cargo clippy -- -D warnings

            - name: Tests
              run: cargo test --lib --examples --verbose

            - name: Docs
              run: cargo doc --verbose

            - name: README updated
              run: |
                cargo install cargo-rdme
                cargo rdme --check

            - name: Minimum Rust version
              run: |
                cargo install cargo-msrv
                cargo msrv verify
